In [45]:
import numpy as np

In [46]:
# 5.1.
# Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
# Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.
A = np.identity(5)
A_ = np.linalg.inv(5*A)
print(A_)

[[ 0.2  0.   0.   0.   0. ]
 [ 0.   0.2  0.   0.   0. ]
 [ 0.   0.   0.2  0.   0. ]
 [-0.  -0.  -0.   0.2 -0. ]
 [ 0.   0.   0.   0.   0.2]]


In [54]:
# 5.2.
# Вычислите определитель:

A = np.array([[1,2,3],[4,0,6],[7,8,9]])
print(np.linalg.det(A))

59.999999999999986


In [55]:
# 5.3.
# 1. Вычислите матрицу, обратную данной:
print(np.linalg.inv(A))
# 2. Приведите пример матрицы 4х4, ранг которой равен 1.
# 0 0 0 2
# 0 0 0 1
# 0 0 0 3
# 0 0 0 4
A = np.array([[0,0,0,2],[0,0,0,1],[0,0,0,3],[0,0,0,4]])
print(A)
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')


[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
[[0 0 0 2]
 [0 0 0 1]
 [0 0 0 3]
 [0 0 0 4]]
Ранг матрицы: 1


In [70]:
# 5.4.
# Вычислите скалярное произведение двух векторов:  
# (1, 5)  и  (2, 8)
a = np.sqrt(1+5**2)
b = np.sqrt(2**2+8**2)

cos_a = np.cos((np.arccos(2/b) - np.arccos(1/a)))
print(f'Косинус а = {cos_a}')
ab = a*b*cos_a
print(f'Cкалярное произведение двух векторов = {ab}')

Косинус а = 0.9988681377244376
Cкалярное произведение двух векторов = 42.0


In [71]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)
s = np.inner(a, b)
print(f'Cкалярное произведение двух векторов = {s}')

Cкалярное произведение двух векторов = 42.0


In [74]:
# 5.5
# Вычислите смешанное произведение трех векторов:
# (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)
v = np.cross(a, b)
mix = np.inner(v, c)
print(f'Cмешанное произведение трех векторов = {mix}')

Cмешанное произведение трех векторов = 228.5
